openapi: 3.1.0
info:
  title: Debug API
  description: |-
    A buggy application to illustrate Docker and Kubernetes features (mainly auto-restart and limits).
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.2.0
#servers:
#  - url: /
externalDocs:
  description: GitHub repository
  url: https://github.com/mborne/debug#readme
tags:
  - name: helpers
    description: Provide debug helpers
  - name: bugs
    description: Simulate bugs
  - name: stress
    description: Run stress test
paths:
  /api/health:
    get:
      tags:
        - helpers
      summary: Test if API is alive
      description: Test if API is alive
      operationId: health
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
  /api/metadata:
    get:
      tags:
        - helpers
      summary: Provides metadata about host or container
      description: Provides hostname, version, arch and color to illustrate version upgrade / downgrade.
      operationId: metadata
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataResponse'

  /api/stats:
    get:
      tags:
        - helpers
      summary: Provides process stats
      description: Provides started_at, memory (process stats) and leaked_buffers_count.
      operationId: stats
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatsResponse'

  /api/headers:
    get:
      tags:
        - helpers
      summary: Show request headers
      description: Allows to illustrate and debug headers added by a LoadBalancer.
      operationId: headers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              type: object

  /api/bug/crash:
    post:
      tags:
        - bugs
      summary: Simulate crash killing process
      description: Allows to illustrate Docker or Kubernetes hability to restart process.
      operationId: simulateCrash
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrashResponse'

  /api/bug/memory-leak:
    post:
      tags:
        - bugs
      summary: Simulate memory leak
      description: Allows to illustrate Docker or Kubernetes hability to limit memory consuption.
      operationId: simulateMemoryLeak
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemoryLeakResponse'

  /api/stress/cpu:
    post:
      tags:
        - stress
      summary: Simulate CPU overload for 30 seconds
      description: Allows to illustrate Docker or Kubernetes hability to limit CPU consuption.
      operationId: stressCpu
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '500':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/stress/memory:
    post:
      tags:
        - stress
      summary: Simulate memory intensive tasks for 30 seconds
      description: Allows to illustrate Docker or Kubernetes hability to limit CPU consuption.
      operationId: stressMemory
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '500':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          examples: ["fail to run cpu stress test (stress-ng missing?)"]
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          examples: ["OK","Oh no!"]
    CrashResponse:
      type: object
      properties:
        message:
          type: string
          examples: ["I'll be back!"]
    MemoryLeakResponse:
      type: object
      properties:
        message:
          type: string
          examples: ["Buffer added to memory"]
        count:
          type: number
          examples: [1,2,3,20]
    MetadataResponse:
      type: object
      properties:
        version:
          type: string
          examples: ["v0.1.3"]
        hostname:
          type: string
          examples: ["localhost"]
        arch:
          type: string
          examples: ["amd64"]
        color:
          type: string
          nullable: true
          examples: [null, "blue", "green"]
    StatsResponse:
      type: object
      properties:
        started_at:
          type: string
          format: date-time
          description: Process start time (ISO 8601)
        memory:
          type: object
          properties:
            rss:
              type: integer
              description: Resident set size (bytes)
            heapUsed:
              type: integer
              description: Heap used (bytes)
        leaked_buffers_count:
          type: integer
          description: Number of buffers kept in memory by the memory-leak endpoint
